# This GitHub action checks whether a new version of this package
# has been registred in the official registry.
# If so, it creates a new _release_:
# https://github.com/JuliaPluto/PlutoSliderServer.jl/releases

name: TagBot

on:
  issue_comment:
    types:
      - created
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
    TagBot:
        if: github.event_name == 'workflow_dispatch' || github.event_name == 'schedule' || github.actor == 'JuliaTagBot'
        runs-on: [ubuntu-latest]
        steps:
            - uses: JuliaRegistries/TagBot@v1
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  lookback: 30
