name: Julia tests

on:
    workflow_dispatch:
    push:
        paths-ignore:
            - '**.md'
        branches:
            - main
    pull_request:
        paths-ignore:
            - '**.md'

jobs:
    test:
        runs-on: ${{ matrix.os }}
        timeout-minutes: 25

        # https://github.com/JuliaRegistries/General/issues/16777
        env:
            JULIA_PKG_SERVER: ''

        # Uncomment if you want to see all results for all OSses. Otherwise, the first failed test cancels all others
        continue-on-error: true
        strategy:
            fail-fast: false
            matrix:
                julia-version: ['1.10', '1']
                os: [ubuntu-latest, windows-latest]

        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v5

            - uses: julia-actions/setup-julia@v2
              with:
                  version: ${{ matrix.julia-version }}
            - uses: julia-actions/cache@v2

            - uses: julia-actions/julia-runtest@v1
